### ISSUE TITLE
Check the role is already attached

### ISSUE THREAD

**Issue by aminespinoza** [ThorstenHans/thorsten-hans.com#20]
Hi! Your article [here](https://github.com/ThorstenHans/thorsten-hans.com/blob/master/_posts/2019-10-04-aks-acr-integration-revisited.md) helped me a lot, a single step to do what I wanted. Is there a command you could use to check the attachment was successfully made? I mean, to check that the operation was accomplished. Thanks!

**Comment by ThorstenHans** [comment]
hey @aminespinoza,

thanks for reaching out and sorry for the long delay.

Easiest way is to use `kubectl run test --image foo.azurecr.io/bar:latest`

maybe there is an `az` command to see it from the outside... which would be the preferable way. I'll look into that and ping once I have an idea/answer for that one.
